import {
  Star,
  Waves,
  Dumbbell,
  Car,
  Shield,
  Wifi,
  Zap,
  Home,
  Trees,
  Camera,
  Users,
  Baby,
  Gamepad2,
  Coffee,
  Wind,
  Flame,
  Droplets,
  Sun,
  Moon,
  Music,
  Tv,
  Phone,
  Mail,
  MapPin,
  Clock,
  Calendar,
  Settings,
  Lock,
  Key,
  Eye,
  Heart,
  ThumbsUp,
  Award,
  Trophy,
  Gift,
  ShoppingCart,
  CreditCard,
  Banknote,
  PiggyBank,
  Utensils,
  ChefHat,
  Wine,
  Pizza,
  IceCream2,
  Mountain,
  Flower,
  Leaf,
  CloudRain,
  Snowflake,
  Thermometer,
  Fan,
  Lightbulb,
  Bed,
  Bath,
  Sofa,
  Lamp,
  LampDesk,
  Scissors,
  Shirt,
  Package,
  Truck,
  Plane,
  Train,
  Bike,
  Fuel,
  Building,
  Church,
  School,
  Hospital,
  Store,
  Factory,
  Warehouse,
  Construction,
  Hammer,
  Wrench,
  Drill,
  Paintbrush,
  Palette,
  Video,
  Headphones,
  Smartphone,
  Laptop,
  Monitor,
  Printer,
  Speaker,
  Mic,
  Radio,
  Disc,
  Volume2,
  VolumeX,
  Play,
  Pause,
  SkipForward,
  SkipBack,
  Repeat,
  Shuffle,
  Search,
  Filter,
  Download,
  Upload,
  Share,
  Copy,
  Clipboard,
  FileText,
  Folder,
  Archive,
  Trash2,
  Edit,
  Save,
  Plus,
  Minus,
  X,
  Check,
  AlertTriangle,
  Info,
  HelpCircle,
  MessageCircle,
  Send,
  Inbox,
  Bell,
  BellOff,
  Flag,
  Bookmark,
  Link,
  ExternalLink,
  Globe,
  Compass,
  Navigation,
  Route,
  Map,
  Locate,
  Target,
  Crosshair,
  Focus,
  Scan,
  QrCode,
  Wallet,
  Coins,
  DollarSign,
  Euro,
  PoundSterling,
  Bitcoin,
  TrendingUp,
  TrendingDown,
  BarChart,
  PieChart,
  LineChart,
  Activity,
  Stethoscope,
  Pill,
  Syringe,
  Bandage,
  Ambulance,
  Cross,
  LifeBuoy,
  Accessibility,
  Glasses,
  Hand,
  Fingerprint,
  User,
  UserPlus,
  UserMinus,
  UserCheck,
  UserX,
  UsersRound,
  UserCog,
  Crown,
  ShieldCheck,
  ShieldAlert,
  ShieldX,
  Unlock,
  KeyRound,
  ScanFace,
  EyeOff,
  Image,
  ImageOff,
  ImagePlus,
  ImageMinus,
  Frame,
  Crop,
  RotateCw,
  RotateCcw,
  FlipHorizontal,
  FlipVertical,
  ZoomIn,
  ZoomOut,
  Maximize,
  Minimize,
  Move,
  MousePointer,
  Grab,
} from "lucide-react";

import { LucideIcon } from "lucide-react";

// Mapa completo de iconos disponibles para amenities
export const iconMap: { [key: string]: LucideIcon } = {
  // Recreación
  Waves: Waves,
  Dumbbell: Dumbbell,
  Gamepad2: Gamepad2,
  Music: Music,
  Tv: Tv,
  Coffee: Coffee,
  Wine: Wine,
  Pizza: Pizza,
  IceCream2: IceCream2,
  Mountain: Mountain,
  Trees: Trees,
  Flower: Flower,

  // Seguridad
  Shield: Shield,
  Camera: Camera,
  Lock: Lock,
  Key: Key,
  Eye: Eye,
  ShieldCheck: ShieldCheck,
  Fingerprint: Fingerprint,
  Bell: Bell,

  // Servicios
  Wifi: Wifi,
  Zap: Zap,
  Droplets: Droplets,
  Flame: Flame,
  Wind: Wind,
  Fan: Fan,
  Lightbulb: Lightbulb,
  Phone: Phone,
  Truck: Truck,
  Package: Package,

  // Transporte
  Car: Car,
  Bike: Bike,
  Plane: Plane,
  Train: Train,
  Fuel: Fuel,

  // Hogar
  Home: Home,
  Bed: Bed,
  Bath: Bath,
  Sofa: Sofa,
  Lamp: Lamp,
  LampDesk: LampDesk,
  Utensils: Utensils,
  ChefHat: ChefHat,

  // Salud
  Heart: Heart,
  Stethoscope: Stethoscope,
  Pill: Pill,
  Cross: Cross,
  Accessibility: Accessibility,

  // Lugares
  Building: Building,
  Church: Church,
  School: School,
  Hospital: Hospital,
  Store: Store,
  ShoppingCart: ShoppingCart,

  // General
  Star: Star,
  Award: Award,
  Trophy: Trophy,
  Gift: Gift,
  ThumbsUp: ThumbsUp,
  Check: Check,
  Settings: Settings,

  // Adicionales comunes
  Users: Users,
  User: User,
  Mail: Mail,
  MapPin: MapPin,
  Clock: Clock,
  Calendar: Calendar,
  Sun: Sun,
  Moon: Moon,
  Thermometer: Thermometer,
  CloudRain: CloudRain,
  Snowflake: Snowflake,
  Leaf: Leaf,
  Baby: Baby,
  Shirt: Shirt,
  Scissors: Scissors,
  Factory: Factory,
  Warehouse: Warehouse,
  Construction: Construction,
  Hammer: Hammer,
  Wrench: Wrench,
  Drill: Drill,
  Paintbrush: Paintbrush,
  Palette: Palette,
  Video: Video,
  Headphones: Headphones,
  Smartphone: Smartphone,
  Laptop: Laptop,
  Monitor: Monitor,
  Printer: Printer,
  Speaker: Speaker,
  Mic: Mic,
  Radio: Radio,
  Disc: Disc,
  Volume2: Volume2,
  VolumeX: VolumeX,
  Play: Play,
  Pause: Pause,
  Search: Search,
  Filter: Filter,
  Download: Download,
  Upload: Upload,
  Share: Share,
  Copy: Copy,
  Clipboard: Clipboard,
  FileText: FileText,
  Folder: Folder,
  Archive: Archive,
  Trash2: Trash2,
  Edit: Edit,
  Save: Save,
  Plus: Plus,
  Minus: Minus,
  X: X,
  AlertTriangle: AlertTriangle,
  Info: Info,
  HelpCircle: HelpCircle,
  MessageCircle: MessageCircle,
  Send: Send,
  Inbox: Inbox,
  BellOff: BellOff,
  Flag: Flag,
  Bookmark: Bookmark,
  Link: Link,
  ExternalLink: ExternalLink,
  Globe: Globe,
  Compass: Compass,
  Navigation: Navigation,
  Route: Route,
  Map: Map,
  Locate: Locate,
  Target: Target,
  Crosshair: Crosshair,
  Focus: Focus,
  Scan: Scan,
  QrCode: QrCode,
  Wallet: Wallet,
  Coins: Coins,
  DollarSign: DollarSign,
  Euro: Euro,
  PoundSterling: PoundSterling,
  Bitcoin: Bitcoin,
  TrendingUp: TrendingUp,
  TrendingDown: TrendingDown,
  BarChart: BarChart,
  PieChart: PieChart,
  LineChart: LineChart,
  Activity: Activity,
  Syringe: Syringe,
  Bandage: Bandage,
  Ambulance: Ambulance,
  LifeBuoy: LifeBuoy,
  Glasses: Glasses,
  Hand: Hand,
  UserPlus: UserPlus,
  UserMinus: UserMinus,
  UserCheck: UserCheck,
  UserX: UserX,
  UsersRound: UsersRound,
  UserCog: UserCog,
  Crown: Crown,
  ShieldAlert: ShieldAlert,
  ShieldX: ShieldX,
  Unlock: Unlock,
  KeyRound: KeyRound,
  ScanFace: ScanFace,
  EyeOff: EyeOff,
  Image: Image,
  ImageOff: ImageOff,
  ImagePlus: ImagePlus,
  ImageMinus: ImageMinus,
  Frame: Frame,
  Crop: Crop,
  RotateCw: RotateCw,
  RotateCcw: RotateCcw,
  FlipHorizontal: FlipHorizontal,
  FlipVertical: FlipVertical,
  ZoomIn: ZoomIn,
  ZoomOut: ZoomOut,
  Maximize: Maximize,
  Minimize: Minimize,
  Move: Move,
  MousePointer: MousePointer,
  Grab: Grab,
  CreditCard: CreditCard,
  Banknote: Banknote,
  PiggyBank: PiggyBank,
  SkipForward: SkipForward,
  SkipBack: SkipBack,
  Repeat: Repeat,
  Shuffle: Shuffle,
};

/**
 * Obtiene el componente de ícono basado en el nombre del ícono
 * @param iconName - Nombre del ícono (debe coincidir con los nombres en iconMap)
 * @returns Componente de ícono de Lucide React
 */
export const getAmenityIcon = (iconName?: string) => {
  if (!iconName) return Star; // Ícono por defecto
  return iconMap[iconName] || Star; // Retorna el ícono solicitado o Star por defecto
};

/**
 * Verifica si un nombre de ícono existe en el mapa
 * @param iconName - Nombre del ícono a verificar
 * @returns true si el ícono existe, false en caso contrario
 */
export const isValidIcon = (iconName: string): boolean => {
  return iconName in iconMap;
};

/**
 * Obtiene todos los nombres de iconos disponibles
 * @returns Array con todos los nombres de iconos disponibles
 */
export const getAvailableIconNames = (): string[] => {
  return Object.keys(iconMap);
};
