// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// Use environment variables with fallback to hardcoded values for development
const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL ||
  "https://nuujznowhmawcvcskzcb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im51dWp6bm93aG1hd2N2Y3NremNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3NTM3NTMsImV4cCI6MjA3NDMyOTc1M30.Fctnqfu0RZplXFQ6fNFZb0WSYSujxkka1_2X32B98Vs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Custom storage that handles localStorage errors gracefully
const customStorage = {
  getItem: (key: string) => {
    try {
      return localStorage.getItem(key);
    } catch (error) {
      console.warn("Error accessing localStorage:", error);
      return null;
    }
  },
  setItem: (key: string, value: string) => {
    try {
      localStorage.setItem(key, value);
    } catch (error) {
      console.warn("Error setting localStorage:", error);
    }
  },
  removeItem: (key: string) => {
    try {
      localStorage.removeItem(key);
    } catch (error) {
      console.warn("Error removing from localStorage:", error);
    }
  },
};

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: customStorage,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
    },
  }
);
